# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imperial/ui/ui_dlgCostoProduccion.ui'
#
# Created: Sun Jul 26 12:52:17 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DlgCostoProduccion(object):
    def setupUi(self, DlgCostoProduccion):
        DlgCostoProduccion.setObjectName(_fromUtf8("DlgCostoProduccion"))
        DlgCostoProduccion.resize(761, 517)
        self.verticalLayout_5 = QtGui.QVBoxLayout(DlgCostoProduccion)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(DlgCostoProduccion)
        self.label_7.setMinimumSize(QtCore.QSize(0, 23))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.fechaCosto = QtGui.QDateEdit(DlgCostoProduccion)
        self.fechaCosto.setCalendarPopup(True)
        self.fechaCosto.setObjectName(_fromUtf8("fechaCosto"))
        self.verticalLayout.addWidget(self.fechaCosto)
        self.label = QtGui.QLabel(DlgCostoProduccion)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.listViewProductos = QtGui.QListView(DlgCostoProduccion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewProductos.sizePolicy().hasHeightForWidth())
        self.listViewProductos.setSizePolicy(sizePolicy)
        self.listViewProductos.setObjectName(_fromUtf8("listViewProductos"))
        self.verticalLayout.addWidget(self.listViewProductos)
        self.label_3 = QtGui.QLabel(DlgCostoProduccion)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.listViewCostosProd = QtGui.QListView(DlgCostoProduccion)
        self.listViewCostosProd.setObjectName(_fromUtf8("listViewCostosProd"))
        self.verticalLayout.addWidget(self.listViewCostosProd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(DlgCostoProduccion)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnAddIngrediente = QtGui.QPushButton(DlgCostoProduccion)
        self.btnAddIngrediente.setObjectName(_fromUtf8("btnAddIngrediente"))
        self.horizontalLayout_2.addWidget(self.btnAddIngrediente)
        self.btnDelIngrediente = QtGui.QPushButton(DlgCostoProduccion)
        self.btnDelIngrediente.setObjectName(_fromUtf8("btnDelIngrediente"))
        self.horizontalLayout_2.addWidget(self.btnDelIngrediente)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableViewIngredientes = QtGui.QTableView(DlgCostoProduccion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewIngredientes.sizePolicy().hasHeightForWidth())
        self.tableViewIngredientes.setSizePolicy(sizePolicy)
        self.tableViewIngredientes.setObjectName(_fromUtf8("tableViewIngredientes"))
        self.verticalLayout_3.addWidget(self.tableViewIngredientes)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lineEditCostoIngredientes = QtGui.QLineEdit(DlgCostoProduccion)
        self.lineEditCostoIngredientes.setReadOnly(True)
        self.lineEditCostoIngredientes.setObjectName(_fromUtf8("lineEditCostoIngredientes"))
        self.horizontalLayout_4.addWidget(self.lineEditCostoIngredientes)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_2 = QtGui.QLabel(DlgCostoProduccion)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lineEditGastosPro = QtGui.QLineEdit(DlgCostoProduccion)
        self.lineEditGastosPro.setInputMask(_fromUtf8(""))
        self.lineEditGastosPro.setObjectName(_fromUtf8("lineEditGastosPro"))
        self.horizontalLayout_5.addWidget(self.lineEditGastosPro)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_4 = QtGui.QLabel(DlgCostoProduccion)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lineEditCant = QtGui.QLineEdit(DlgCostoProduccion)
        self.lineEditCant.setObjectName(_fromUtf8("lineEditCant"))
        self.horizontalLayout_6.addWidget(self.lineEditCant)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_6 = QtGui.QLabel(DlgCostoProduccion)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtGui.QLabel(DlgCostoProduccion)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.lineEditTotal = QtGui.QLineEdit(DlgCostoProduccion)
        self.lineEditTotal.setObjectName(_fromUtf8("lineEditTotal"))
        self.horizontalLayout_7.addWidget(self.lineEditTotal)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.plainTEDesc = QtGui.QPlainTextEdit(DlgCostoProduccion)
        self.plainTEDesc.setTabChangesFocus(True)
        self.plainTEDesc.setObjectName(_fromUtf8("plainTEDesc"))
        self.verticalLayout_2.addWidget(self.plainTEDesc)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(DlgCostoProduccion)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnImprimir = QtGui.QPushButton(DlgCostoProduccion)
        self.btnImprimir.setObjectName(_fromUtf8("btnImprimir"))
        self.horizontalLayout_3.addWidget(self.btnImprimir)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.NuevoPushButton = QtGui.QPushButton(DlgCostoProduccion)
        self.NuevoPushButton.setObjectName(_fromUtf8("NuevoPushButton"))
        self.horizontalLayout_3.addWidget(self.NuevoPushButton)
        self.btnGrabarDatos = QtGui.QPushButton(DlgCostoProduccion)
        self.btnGrabarDatos.setObjectName(_fromUtf8("btnGrabarDatos"))
        self.horizontalLayout_3.addWidget(self.btnGrabarDatos)
        self.btnCerrar = QtGui.QPushButton(DlgCostoProduccion)
        self.btnCerrar.setObjectName(_fromUtf8("btnCerrar"))
        self.horizontalLayout_3.addWidget(self.btnCerrar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.label_7.setBuddy(self.fechaCosto)
        self.label.setBuddy(self.listViewProductos)

        self.retranslateUi(DlgCostoProduccion)
        QtCore.QMetaObject.connectSlotsByName(DlgCostoProduccion)
        DlgCostoProduccion.setTabOrder(self.fechaCosto, self.listViewProductos)
        DlgCostoProduccion.setTabOrder(self.listViewProductos, self.tableViewIngredientes)
        DlgCostoProduccion.setTabOrder(self.tableViewIngredientes, self.btnAddIngrediente)
        DlgCostoProduccion.setTabOrder(self.btnAddIngrediente, self.btnDelIngrediente)
        DlgCostoProduccion.setTabOrder(self.btnDelIngrediente, self.lineEditCostoIngredientes)
        DlgCostoProduccion.setTabOrder(self.lineEditCostoIngredientes, self.lineEditGastosPro)
        DlgCostoProduccion.setTabOrder(self.lineEditGastosPro, self.lineEditCant)
        DlgCostoProduccion.setTabOrder(self.lineEditCant, self.lineEditTotal)
        DlgCostoProduccion.setTabOrder(self.lineEditTotal, self.btnGrabarDatos)
        DlgCostoProduccion.setTabOrder(self.btnGrabarDatos, self.btnCerrar)

    def retranslateUi(self, DlgCostoProduccion):
        DlgCostoProduccion.setWindowTitle(_translate("DlgCostoProduccion", "Costos de producción", None))
        self.label_7.setText(_translate("DlgCostoProduccion", "&Fecha:", None))
        self.fechaCosto.setDisplayFormat(_translate("DlgCostoProduccion", "dd-MM-yyyy", None))
        self.label.setText(_translate("DlgCostoProduccion", "&Producto:", None))
        self.label_3.setText(_translate("DlgCostoProduccion", "Costos x producto: ", None))
        self.label_5.setText(_translate("DlgCostoProduccion", "Ingredientes:", None))
        self.btnAddIngrediente.setText(_translate("DlgCostoProduccion", "Agregar ingrediente", None))
        self.btnDelIngrediente.setText(_translate("DlgCostoProduccion", "&Quitar ingrediente", None))
        self.label_2.setText(_translate("DlgCostoProduccion", "Gastos de producción:", None))
        self.label_4.setText(_translate("DlgCostoProduccion", "Cantidad:", None))
        self.label_6.setText(_translate("DlgCostoProduccion", "Total:", None))
        self.label_8.setText(_translate("DlgCostoProduccion", "Costo Total ingredientes:", None))
        self.btnImprimir.setText(_translate("DlgCostoProduccion", "&imprimir", None))
        self.NuevoPushButton.setText(_translate("DlgCostoProduccion", "Grabar &Nuevo Costo", None))
        self.btnGrabarDatos.setText(_translate("DlgCostoProduccion", "&Grabar costo", None))
        self.btnCerrar.setText(_translate("DlgCostoProduccion", "&Cerrar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DlgCostoProduccion = QtGui.QDialog()
    ui = Ui_DlgCostoProduccion()
    ui.setupUi(DlgCostoProduccion)
    DlgCostoProduccion.show()
    sys.exit(app.exec_())

