# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imperial/ui/ui_dlgAddVendedorProv.ui'
#
# Created: Fri Jul 17 00:08:02 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DlgAddVendedorProv(object):
    def setupUi(self, DlgAddVendedorProv):
        DlgAddVendedorProv.setObjectName(_fromUtf8("DlgAddVendedorProv"))
        DlgAddVendedorProv.resize(445, 346)
        self.verticalLayout = QtGui.QVBoxLayout(DlgAddVendedorProv)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.celularLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.celularLineEdit.setMaxLength(18)
        self.celularLineEdit.setObjectName(_fromUtf8("celularLineEdit"))
        self.horizontalLayout_6.addWidget(self.celularLineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 1, 1, 1)
        self.vendedorPushButton = QtGui.QPushButton(DlgAddVendedorProv)
        self.vendedorPushButton.setObjectName(_fromUtf8("vendedorPushButton"))
        self.gridLayout.addWidget(self.vendedorPushButton, 9, 0, 1, 1)
        self.nombreLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.nombreLabel.setObjectName(_fromUtf8("nombreLabel"))
        self.gridLayout.addWidget(self.nombreLabel, 0, 0, 1, 1)
        self.barrioLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.barrioLineEdit.setMaxLength(30)
        self.barrioLineEdit.setObjectName(_fromUtf8("barrioLineEdit"))
        self.gridLayout.addWidget(self.barrioLineEdit, 3, 1, 1, 1)
        self.barrioLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.barrioLabel.setObjectName(_fromUtf8("barrioLabel"))
        self.gridLayout.addWidget(self.barrioLabel, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.telefonoLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.telefonoLineEdit.setMaxLength(18)
        self.telefonoLineEdit.setObjectName(_fromUtf8("telefonoLineEdit"))
        self.horizontalLayout_5.addWidget(self.telefonoLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.alturaLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.alturaLineEdit.setText(_fromUtf8(""))
        self.alturaLineEdit.setMaxLength(8)
        self.alturaLineEdit.setObjectName(_fromUtf8("alturaLineEdit"))
        self.horizontalLayout_4.addWidget(self.alturaLineEdit)
        self.pisoLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.pisoLabel.setObjectName(_fromUtf8("pisoLabel"))
        self.horizontalLayout_4.addWidget(self.pisoLabel)
        self.pisoLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.pisoLineEdit.setText(_fromUtf8(""))
        self.pisoLineEdit.setMaxLength(5)
        self.pisoLineEdit.setObjectName(_fromUtf8("pisoLineEdit"))
        self.horizontalLayout_4.addWidget(self.pisoLineEdit)
        self.deptoLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.deptoLabel.setObjectName(_fromUtf8("deptoLabel"))
        self.horizontalLayout_4.addWidget(self.deptoLabel)
        self.deptoLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.deptoLineEdit.setText(_fromUtf8(""))
        self.deptoLineEdit.setMaxLength(5)
        self.deptoLineEdit.setObjectName(_fromUtf8("deptoLineEdit"))
        self.horizontalLayout_4.addWidget(self.deptoLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ciudadLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.ciudadLineEdit.setReadOnly(True)
        self.ciudadLineEdit.setObjectName(_fromUtf8("ciudadLineEdit"))
        self.horizontalLayout_2.addWidget(self.ciudadLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.emailLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.gridLayout.addWidget(self.emailLabel, 8, 0, 1, 1)
        self.celularLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.celularLabel.setObjectName(_fromUtf8("celularLabel"))
        self.gridLayout.addWidget(self.celularLabel, 7, 0, 1, 1)
        self.telefonoLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.telefonoLabel.setObjectName(_fromUtf8("telefonoLabel"))
        self.gridLayout.addWidget(self.telefonoLabel, 6, 0, 1, 1)
        self.provLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.provLabel.setObjectName(_fromUtf8("provLabel"))
        self.gridLayout.addWidget(self.provLabel, 5, 0, 1, 1)
        self.direccionLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.direccionLabel.setObjectName(_fromUtf8("direccionLabel"))
        self.gridLayout.addWidget(self.direccionLabel, 1, 0, 1, 1)
        self.alturaLabel = QtGui.QLabel(DlgAddVendedorProv)
        self.alturaLabel.setObjectName(_fromUtf8("alturaLabel"))
        self.gridLayout.addWidget(self.alturaLabel, 2, 0, 1, 1)
        self.direccionLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.direccionLineEdit.setMaxLength(40)
        self.direccionLineEdit.setObjectName(_fromUtf8("direccionLineEdit"))
        self.gridLayout.addWidget(self.direccionLineEdit, 1, 1, 1, 1)
        self.nombreLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.nombreLineEdit.setMaxLength(40)
        self.nombreLineEdit.setObjectName(_fromUtf8("nombreLineEdit"))
        self.gridLayout.addWidget(self.nombreLineEdit, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.provLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.provLineEdit.setReadOnly(True)
        self.provLineEdit.setObjectName(_fromUtf8("provLineEdit"))
        self.horizontalLayout_3.addWidget(self.provLineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.ciudadPushButton = QtGui.QPushButton(DlgAddVendedorProv)
        self.ciudadPushButton.setObjectName(_fromUtf8("ciudadPushButton"))
        self.gridLayout.addWidget(self.ciudadPushButton, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.emailLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.emailLineEdit.setMaxLength(50)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.horizontalLayout_7.addWidget(self.emailLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 1, 1, 1)
        self.vendedorLineEdit = QtGui.QLineEdit(DlgAddVendedorProv)
        self.vendedorLineEdit.setObjectName(_fromUtf8("vendedorLineEdit"))
        self.gridLayout.addWidget(self.vendedorLineEdit, 9, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(DlgAddVendedorProv)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtGui.QDialogButtonBox(DlgAddVendedorProv)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.nombreLabel.setBuddy(self.nombreLineEdit)
        self.barrioLabel.setBuddy(self.barrioLineEdit)
        self.pisoLabel.setBuddy(self.pisoLineEdit)
        self.deptoLabel.setBuddy(self.deptoLineEdit)
        self.emailLabel.setBuddy(self.emailLineEdit)
        self.celularLabel.setBuddy(self.celularLineEdit)
        self.telefonoLabel.setBuddy(self.telefonoLineEdit)
        self.provLabel.setBuddy(self.provLineEdit)
        self.direccionLabel.setBuddy(self.direccionLineEdit)
        self.alturaLabel.setBuddy(self.alturaLineEdit)

        self.retranslateUi(DlgAddVendedorProv)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DlgAddVendedorProv.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DlgAddVendedorProv.reject)
        QtCore.QObject.connect(self.nombreLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.direccionLineEdit.selectAll)
        QtCore.QObject.connect(self.nombreLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.direccionLineEdit.setFocus)
        QtCore.QObject.connect(self.direccionLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.alturaLineEdit.selectAll)
        QtCore.QObject.connect(self.direccionLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.alturaLineEdit.setFocus)
        QtCore.QObject.connect(self.alturaLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.pisoLineEdit.selectAll)
        QtCore.QObject.connect(self.alturaLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.pisoLineEdit.setFocus)
        QtCore.QObject.connect(self.pisoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.deptoLineEdit.selectAll)
        QtCore.QObject.connect(self.pisoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.deptoLineEdit.setFocus)
        QtCore.QObject.connect(self.deptoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.barrioLineEdit.selectAll)
        QtCore.QObject.connect(self.deptoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.barrioLineEdit.setFocus)
        QtCore.QObject.connect(self.barrioLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.ciudadPushButton.setFocus)
        QtCore.QObject.connect(self.provLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.telefonoLineEdit.selectAll)
        QtCore.QObject.connect(self.provLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.telefonoLineEdit.setFocus)
        QtCore.QObject.connect(self.telefonoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.celularLineEdit.selectAll)
        QtCore.QObject.connect(self.telefonoLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.celularLineEdit.setFocus)
        QtCore.QObject.connect(self.celularLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.emailLineEdit.selectAll)
        QtCore.QObject.connect(self.celularLineEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.emailLineEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(DlgAddVendedorProv)
        DlgAddVendedorProv.setTabOrder(self.nombreLineEdit, self.direccionLineEdit)
        DlgAddVendedorProv.setTabOrder(self.direccionLineEdit, self.alturaLineEdit)
        DlgAddVendedorProv.setTabOrder(self.alturaLineEdit, self.pisoLineEdit)
        DlgAddVendedorProv.setTabOrder(self.pisoLineEdit, self.deptoLineEdit)
        DlgAddVendedorProv.setTabOrder(self.deptoLineEdit, self.barrioLineEdit)
        DlgAddVendedorProv.setTabOrder(self.barrioLineEdit, self.ciudadPushButton)
        DlgAddVendedorProv.setTabOrder(self.ciudadPushButton, self.ciudadLineEdit)
        DlgAddVendedorProv.setTabOrder(self.ciudadLineEdit, self.provLineEdit)
        DlgAddVendedorProv.setTabOrder(self.provLineEdit, self.telefonoLineEdit)
        DlgAddVendedorProv.setTabOrder(self.telefonoLineEdit, self.celularLineEdit)
        DlgAddVendedorProv.setTabOrder(self.celularLineEdit, self.emailLineEdit)
        DlgAddVendedorProv.setTabOrder(self.emailLineEdit, self.buttonBox)

    def retranslateUi(self, DlgAddVendedorProv):
        DlgAddVendedorProv.setWindowTitle(_translate("DlgAddVendedorProv", "Agregar proveedor", None))
        self.vendedorPushButton.setText(_translate("DlgAddVendedorProv", "&Proveedor", None))
        self.nombreLabel.setText(_translate("DlgAddVendedorProv", "&Vendedor:", None))
        self.barrioLabel.setText(_translate("DlgAddVendedorProv", "&Barrio:", None))
        self.pisoLabel.setText(_translate("DlgAddVendedorProv", "Piso:", None))
        self.deptoLabel.setText(_translate("DlgAddVendedorProv", "Depto:", None))
        self.emailLabel.setText(_translate("DlgAddVendedorProv", "E-mail:", None))
        self.celularLabel.setText(_translate("DlgAddVendedorProv", "Celular:", None))
        self.telefonoLabel.setText(_translate("DlgAddVendedorProv", "Teléfono:", None))
        self.provLabel.setText(_translate("DlgAddVendedorProv", "Provincia:", None))
        self.direccionLabel.setText(_translate("DlgAddVendedorProv", "Dirección:", None))
        self.alturaLabel.setText(_translate("DlgAddVendedorProv", "Altura:", None))
        self.ciudadPushButton.setText(_translate("DlgAddVendedorProv", "Ciudad...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DlgAddVendedorProv = QtGui.QDialog()
    ui = Ui_DlgAddVendedorProv()
    ui.setupUi(DlgAddVendedorProv)
    DlgAddVendedorProv.show()
    sys.exit(app.exec_())

